### ISSUE TITLE
Operational Error: Net-Lib error during Operation now in progress

### ISSUE THREAD

**Issue by JPGlaser** [lsst/lsst_sims#1]
To Whom it My Concern,

Currently I am working getting the quite nice handy work that is lsst_sims to run on the local Drexel University RedHat cluster. The LSST Stack (ver. 10.0) and lsst_sims (ver. master-g69b085209b+572) are installed and setup like normal before each run (a path check is done to confirm this before I run anything). To test the install, I go ahead and read the first tutorial and run it as a main process in python to generate sample catalogs.

However, each script that is run returns the same operational error at the end of a long string of a dependency cascade. Has anyone seen this before? Much thanks in advance!

~ Joe

``` bash
[jglaser@dirac lsst_catSim_040215]$ python /home/jglaser/lsst/Linux64/sims_catUtils/master-gce0eaba1be/examples/tutorials/tutorial00.py
Traceback (most recent call last):
  File "/home/jglaser/lsst/Linux64/sims_catUtils/master-gce0eaba1be/examples/tutorials/tutorial00.py", line 9, in <module>
    myGalaxyDB = CatalogDBObject.from_objid('galaxyTiled')
  File "/home/jglaser/lsst/Linux64/sims_catalogs_generation/master-gcc73a46424/python/lsst/sims/catalogs/generation/db/dbConnection.py", line 324, in from_objid
    return cls(*args, **kwargs)
  File "/home/jglaser/lsst/Linux64/sims_catalogs_generation/master-gcc73a46424/python/lsst/sims/catalogs/generation/db/dbConnection.py", line 344, in __init__
    self._get_table()
  File "/home/jglaser/lsst/Linux64/sims_catalogs_generation/master-gcc73a46424/python/lsst/sims/catalogs/generation/db/dbConnection.py", line 379, in _get_table
    autoload=True)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 354, in __new__
    table._init(name, metadata, *args, **kw)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 427, in _init
    self._autoload(metadata, autoload_with, include_columns)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 451, in _autoload
    self, include_columns, exclude_columns
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1732, in run_callable
    with self.contextual_connect() as conn:
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1799, in contextual_connect
    self.pool.connect(),
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 338, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 641, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 440, in checkout
    rec = pool._do_get()
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 961, in _do_get
    return self._create_connection()
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 285, in _create_connection
    return _ConnectionRecord(self)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 411, in __init__
    self.connection = self.__connect()
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/pool.py", line 537, in __connect
    connection = self.__pool._creator()
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 96, in connect
    connection_invalidated=invalidated
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 90, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/jglaser/lsst/Linux64/anaconda/2.1.0/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 377, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "pymssql.pyx", line 577, in pymssql.connect (pymssql.c:9703)
    raise OperationalError(e.args[0])
sqlalchemy.exc.OperationalError: (OperationalError) (20009, 'Net-Lib error during Operation now in progress') None None
```

**Comment by SimonKrughoff** [comment]
@JPGlaser These scripts are trying to query a database at University of Washington.  We are working on a better model, but the current security model is to whitelist the IPs of trusted sites.  If you send me an IP range and netmask to krughoff at uw.edu, I can get you whitelisted.

**Comment by JPGlaser** [comment]
Thanks for the quick reply @SimonKrughoff. I'll send over that information for the whitelist ASAP. I was wondering where it was getting its base catalog from, so this clears up a lot of questions I was having.

~ Joe
